---
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/deploy-ansible-galaxy-collection
#
name: Release and deploy collection
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: Deploy Ansible Galaxy Collection
        uses: artis3n/ansible_galaxy_collection@v2.8.1
        with:
          publish: false

      # https://github.com/marketplace/actions/gh-release
      # https://github.com/softprops/action-gh-release
      - name: Upload files to a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tar.gz"
        if: startsWith(github.ref, 'refs/tags/')
