---
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/deploy-ansible-galaxy-collection
#
name: Release and deploy collection
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true
          submodules: recursive

      - name: galaxy version
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          sed -i "s/^version:.*$/version: ${RELEASE_VERSION#v}/" galaxy.yml
        if: startsWith(github.ref, 'refs/tags/')

      # https://github.com/marketplace/actions/ansible-test
      # collection-src-directory: A pre-checked out collection directory that's already on disk
      #- name: ansible-test
      #  uses: ansible-community/ansible-test-gh-action@v1.7.0
      #  with:
      #    ansible-core-version: stable-2.13
      #    collection-src-directory: /home/runner/work/gohitech.core/gohitech.core
      #    testing-type: sanity

      - name: Deploy Ansible Galaxy Collection
        uses: artis3n/ansible_galaxy_collection@v2.8.1
        with:
          api_key: NOT_REQUIRED_GALAXY_API_KEY
          publish: false

      # https://github.com/marketplace/actions/gh-release
      # https://github.com/softprops/action-gh-release
      - name: Upload files to a GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tar.gz"
        if: startsWith(github.ref, 'refs/tags/')
